//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiciosSoap")]
    public interface ServiciosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Consumo.ServiceReference1.HelloWorldResponse HelloWorld(Consumo.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Consumo.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        Consumo.ServiceReference1.SaludarResponse Saludar(Consumo.ServiceReference1.SaludarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> SaludarAsync(Consumo.ServiceReference1.SaludarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        Consumo.ServiceReference1.GuardarLogResponse GuardarLog(Consumo.ServiceReference1.GuardarLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> GuardarLogAsync(Consumo.ServiceReference1.GuardarLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Consumo.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Consumo.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Saludar", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.SaludarRequestBody Body;
        
        public SaludarRequest() {
        }
        
        public SaludarRequest(Consumo.ServiceReference1.SaludarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public SaludarRequestBody() {
        }
        
        public SaludarRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.SaludarResponseBody Body;
        
        public SaludarResponse() {
        }
        
        public SaludarResponse(Consumo.ServiceReference1.SaludarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaludarResult;
        
        public SaludarResponseBody() {
        }
        
        public SaludarResponseBody(string SaludarResult) {
            this.SaludarResult = SaludarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLog", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarLogRequestBody Body;
        
        public GuardarLogRequest() {
        }
        
        public GuardarLogRequest(Consumo.ServiceReference1.GuardarLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public GuardarLogRequestBody() {
        }
        
        public GuardarLogRequestBody(string mensaje) {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarLogResponseBody Body;
        
        public GuardarLogResponse() {
        }
        
        public GuardarLogResponse(Consumo.ServiceReference1.GuardarLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarLogResult;
        
        public GuardarLogResponseBody() {
        }
        
        public GuardarLogResponseBody(string GuardarLogResult) {
            this.GuardarLogResult = GuardarLogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosSoapChannel : Consumo.ServiceReference1.ServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosSoapClient : System.ServiceModel.ClientBase<Consumo.ServiceReference1.ServiciosSoap>, Consumo.ServiceReference1.ServiciosSoap {
        
        public ServiciosSoapClient() {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.HelloWorldResponse Consumo.ServiceReference1.ServiciosSoap.HelloWorld(Consumo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Consumo.ServiceReference1.HelloWorldRequest inValue = new Consumo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Consumo.ServiceReference1.HelloWorldRequestBody();
            Consumo.ServiceReference1.HelloWorldResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> Consumo.ServiceReference1.ServiciosSoap.HelloWorldAsync(Consumo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Consumo.ServiceReference1.HelloWorldRequest inValue = new Consumo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Consumo.ServiceReference1.HelloWorldRequestBody();
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.SaludarResponse Consumo.ServiceReference1.ServiciosSoap.Saludar(Consumo.ServiceReference1.SaludarRequest request) {
            return base.Channel.Saludar(request);
        }
        
        public string Saludar(string nombre) {
            Consumo.ServiceReference1.SaludarRequest inValue = new Consumo.ServiceReference1.SaludarRequest();
            inValue.Body = new Consumo.ServiceReference1.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            Consumo.ServiceReference1.SaludarResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).Saludar(inValue);
            return retVal.Body.SaludarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> Consumo.ServiceReference1.ServiciosSoap.SaludarAsync(Consumo.ServiceReference1.SaludarRequest request) {
            return base.Channel.SaludarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> SaludarAsync(string nombre) {
            Consumo.ServiceReference1.SaludarRequest inValue = new Consumo.ServiceReference1.SaludarRequest();
            inValue.Body = new Consumo.ServiceReference1.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).SaludarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.GuardarLogResponse Consumo.ServiceReference1.ServiciosSoap.GuardarLog(Consumo.ServiceReference1.GuardarLogRequest request) {
            return base.Channel.GuardarLog(request);
        }
        
        public string GuardarLog(string mensaje) {
            Consumo.ServiceReference1.GuardarLogRequest inValue = new Consumo.ServiceReference1.GuardarLogRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarLogRequestBody();
            inValue.Body.mensaje = mensaje;
            Consumo.ServiceReference1.GuardarLogResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarLog(inValue);
            return retVal.Body.GuardarLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> Consumo.ServiceReference1.ServiciosSoap.GuardarLogAsync(Consumo.ServiceReference1.GuardarLogRequest request) {
            return base.Channel.GuardarLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> GuardarLogAsync(string mensaje) {
            Consumo.ServiceReference1.GuardarLogRequest inValue = new Consumo.ServiceReference1.GuardarLogRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarLogRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarLogAsync(inValue);
        }
    }
}
